"""add_market_data

Revision ID: 36e8b32825f7
Revises: f568e543e854
Create Date: 2026-03-26 01:36:16.299344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e8b32825f7'
down_revision: Union[str, Sequence[str], None] = 'f568e543e854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchanges', 'work_in_Russia', new_column_name='work_in_russia')
    op.add_column('exchanges', sa.Column('trust_score', sa.Integer(), nullable=True))
    op.add_column('exchanges', sa.Column('btc_price', sa.Float(), nullable=True))
    op.add_column('exchanges', sa.Column('eth_price', sa.Float(), nullable=True))
    op.add_column('exchanges', sa.Column('sol_price', sa.Float(), nullable=True))
    op.add_column('exchanges', sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'FAILED', 'FINISHED', name='sagastatus', native_enum=False), nullable=False))
    op.create_unique_constraint(None, 'exchanges', ['exchange_name'])
    op.add_column('users', sa.Column('age', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    op.drop_constraint(None, 'exchanges', type_='unique')
    op.drop_column('exchanges', 'status')
    op.drop_column('exchanges', 'sol_price')
    op.drop_column('exchanges', 'eth_price')
    op.drop_column('exchanges', 'btc_price')
    op.drop_column('exchanges', 'trust_score')
    op.drop_column('exchanges', 'work_in_russia')
    op.alter_column('exchanges', 'work_in_russia', new_column_name='work_in_Russia')
    # ### end Alembic commands ###
