"""added saga status in sql model

Revision ID: 45e1a6fd2fec
Revises: 477d315fd57a
Create Date: 2026-03-12 23:08:11.448195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e1a6fd2fec'
down_revision: Union[str, Sequence[str], None] = '477d315fd57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'FAILED', name='sagastatus', native_enum=False), nullable=False))
    op.alter_column('exchanges', 'trust_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exchanges', 'btc_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('exchanges', 'eth_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('exchanges', 'sol_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchanges', 'sol_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('exchanges', 'eth_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('exchanges', 'btc_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('exchanges', 'trust_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('exchanges', 'status')
    # ### end Alembic commands ###
