"""add data and saga

Revision ID: cb126b9f53e0
Revises: de3dd0bd8c29
Create Date: 2026-03-18 12:39:30.430851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb126b9f53e0'
down_revision: Union[str, Sequence[str], None] = 'de3dd0bd8c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('trust_score', sa.Integer(), nullable=True))
    op.add_column('exchanges', sa.Column('btc_price', sa.Float(), nullable=True))
    op.add_column('exchanges', sa.Column('eth_price', sa.Float(), nullable=True))
    op.add_column('exchanges', sa.Column('sol_price', sa.Float(), nullable=True))
    op.add_column('exchanges', sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'FAILED', name='sagastatus', native_enum=False), nullable=False))
    op.alter_column('users', 'age',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
                postgresql_using='age::date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'age',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
                    postgresql_using='age::varchar')
    op.drop_column('exchanges', 'status')
    op.drop_column('exchanges', 'sol_price')
    op.drop_column('exchanges', 'eth_price')
    op.drop_column('exchanges', 'btc_price')
    op.drop_column('exchanges', 'trust_score')
    # ### end Alembic commands ###
